[build]
  command = """
    python -m pip install --upgrade pip &&
    pip install -r requirements.txt &&
    mkdir -p public &&
    cp -r templates/* public/ &&
    cp -r static public/
  """
  publish = "public"

[build.environment]
  PYTHON_VERSION = "3.9"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self' 'unsafe-inline' 'unsafe-eval' *.google-analytics.com *.googleapis.com *.gstatic.com; img-src 'self' data: *.google-analytics.com *.googleapis.com *.gstatic.com;"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"