[build]
  command = """
    pip install -r requirements.txt &&
    python sitemap_generator.py &&
    cp -r templates/* public/
  """
  publish = "public"
  functions = "netlify/functions"

[build.environment]
  PYTHON_VERSION = "3.9"
  NODE_VERSION = "16"

[[redirects]]
  from = "/*"
  to = "/home/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self' 'unsafe-inline' 'unsafe-eval' *.google-analytics.com *.googleapis.com *.gstatic.com; img-src 'self' data: *.google-analytics.com *.googleapis.com *.gstatic.com;"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"